version: '3'

services:
  fix-mongodb-permissions:
    image: 'alpine:3.10'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - "mongo-data:/bitnami"

  primary-database:
    image: 'bitnami/mongodb:latest'
    restart: on-failure
    depends_on:
      - fix-mongodb-permissions
    networks:
      - general-network
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s
    ports:
      - '27018:27017'
    volumes:
      - 'mongo-data:/bitnami'
    environment:
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=Passw0rd
      - MONGODB_DATABASE=api-monitor

  server:
    build:
      context: .
    restart: always
    networks:
      - general-network
    volumes:
      - ./:/app/
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      PORT: 3000
      MONGO_URL: 'mongodb://admin:Passw0rd@primary-database:27017/api-monitor'
      JWT_SECRET: JWT_SECRET
      MAILER_CONFIG: >
        {
          "username": "",
          "password": ""
        }

    command: ['npm', 'run', 'dev']

volumes:
  mongo-data:
    driver: local

networks:
  general-network:
